### PR TITLE
Replace SLF4J with System.err.println to improve library compatibility (fixes #30).

### LINKED ISSUE #30: SLF4J API version used for logging is incompatible with projects that use 1.7.x provider versions
### Bug

When attempting to use this library in a project that uses 1.7.25 SLF4j API/providers, SLF4J fails to find a binding:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/slf4j-test/target/slf4j-test-1.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

### clp-ffi version

0.3.3

### Environment

* Ubuntu 20.04
* Java 11

### Reproduction steps

* Create a Java app that depends on this library and an SFL4J 1.7.25 provider (e.g., slf4j-log4j12.
* Attempt to run the app.

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# References

#30

# Description

Since SLF4J 2.0 seems to be [incompatible](https://www.slf4j.org/faq.html#changesInVersion200) with SLF4J 1.7.x providers, and this library may be used in projects that still use SLF4J 1.7.x, this PR replaces SLF4J with simple `System.err.println` statements.

Unfortunately, this may make debugging more difficult if users only collect their logs through logging libraries and ignore console output.

This PR also logs an error when `System.loadLibrary` fails (previously it was swallowed).

# Validation performed

Validated that errors are printed to stderr when the library isn't found during unit tests:
* Changed `java.library.path` to a non-existent path in `maven-surefire-plugin`'s configuration in `pom.xml`
* Ran the unit tests and validated that the relevant errors are printed.

### CODE REVIEW

File: src/main/java/com/yscope/clp/compressorfrontend/NativeLibraryLoader.java [hunk 1]
```diff
@@ -82,4 +81,8 @@ private static URL getLibUrlInJar() {
 
     return null;
   }
+
+  private static void logError(String message) {
+    System.err.println("clp-ffi: " + message);
```
Comment (jackluo923) [inline src/main/java/com/yscope/clp/compressorfrontend/NativeLibraryLoader.java]: Can we print out timestamp here?

**Review by jackluo923 — CHANGES_REQUESTED** [review]

File: src/main/java/com/yscope/clp/compressorfrontend/NativeLibraryLoader.java (hunk 1 above)
Comment (kirkrodrigues) [reply src/main/java/com/yscope/clp/compressorfrontend/NativeLibraryLoader.java]: Is this format okay?

`2023-04-09T01:18:57.823Z clp-ffi: Failed to find native library in JAR.`

**Review by jackluo923 — APPROVED** [review]
